In [13]:
import pandas as pd
import numpy as np

## NAV History Data Quality Assessment

In [14]:
nav = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\02_nav_history.csv")
nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

# Dataset Overview

In [15]:
nav.shape

(46000, 3)

In [5]:
nav.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [8]:
nav.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

# Validate Date Column

In [27]:
nav.dtypes

amfi_code             int64
date         datetime64[us]
nav                 float64
dtype: object

In [26]:
nav["date"] = pd.to_datetime(nav["date"])

# Missing Values Check

In [31]:
nav.isnull().sum()

# No missing NAV values found.
# Forward fill not required

amfi_code    0
date         0
nav          0
dtype: int64

# Duplicate Check

In [32]:
nav.duplicated().sum()

# No duplicate records found.

np.int64(0)

# Validate NAV > 0

In [34]:
(nav["nav"] <= 0).sum()

# All NAV values are greater than zero.

np.int64(0)

# Sort Data

In [ ]:
nav = nav.sort_values(
    by=["amfi_code", "date"])

# Save Processed File

In [38]:
nav.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_nav_history.csv",
    index=False)

# investor_transactions.csv

In [55]:
inv_trans = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\08_investor_transactions.csv")
inv_trans.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

# Understand Dataset

In [56]:
inv_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [59]:
inv_trans.dtypes

investor_id                      str
transaction_date      datetime64[us]
amfi_code                      int64
transaction_type                 str
amount_inr                     int64
state                            str
city                             str
city_tier                        str
age_group                        str
gender                           str
annual_income_lakh           float64
payment_mode                     str
kyc_status                       str
dtype: object

# Fix Date Formats

In [58]:
inv_trans["transaction_date"] = pd.to_datetime(inv_trans["transaction_date"])

In [60]:
inv_trans.dtypes

investor_id                      str
transaction_date      datetime64[us]
amfi_code                      int64
transaction_type                 str
amount_inr                     int64
state                            str
city                             str
city_tier                        str
age_group                        str
gender                           str
annual_income_lakh           float64
payment_mode                     str
kyc_status                       str
dtype: object

# Standardise transaction_type

In [63]:
inv_trans["transaction_type"].value_counts()

transaction_type
SIP           19716
LUMPSUM        8095
REDEMPTION     4967
Name: count, dtype: int64

In [62]:
inv_trans["transaction_type"] = (inv_trans["transaction_type"].str.strip().str.upper())

# Validate Amount > 0

In [65]:
(inv_trans["amount_inr"] <= 0).sum()

# all amount greater than zero

np.int64(0)

# Check KYC Status

In [66]:
inv_trans["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

# Check Missing Values

In [67]:
inv_trans.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

# Duplicate Check

In [68]:
inv_trans.duplicated().sum()

np.int64(0)

# Save Cleaned File

In [70]:
inv_trans.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_investor_transactions.csv",index=False)

# Scheme Performance Dataset

In [71]:
sch_perf = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\07_scheme_performance.csv")

In [77]:
sch_perf.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

# Validate Datatype

In [74]:
sch_perf.dtypes

# return column values already in numeric type

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

# Flag Negative Sharp Ratio

In [78]:
(sch_perf["sharpe_ratio"] < 0).sum()

# No negative Sharpe Ratios found.
# No flagging is required

np.int64(0)

# Validate Expense Ratio

In [84]:
sch_perf["expense_ratio_pct"].describe()

# all expense ratio pct is within a desired range (0.1% - 2.5%)

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

# Check Missing Values

In [85]:
sch_perf.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

# Duplicate Check

In [87]:
sch_perf.duplicated().sum()

np.int64(0)

# Save Cleaned Dataset

In [89]:
sch_perf.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_scheme_performance.csv",index=False)

# Fund Master Dataset

In [92]:
fund_master = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\01_fund_master.csv")

In [93]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

# Perform Checks

In [94]:
fund_master.shape

(40, 15)

In [95]:
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [96]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [97]:
fund_master.duplicated().sum()

np.int64(0)

# Validate

In [98]:
fund_master["risk_category"].unique()

<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [99]:
fund_master["category"].unique()

<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

In [100]:
fund_master["sub_category"].unique()

<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

In [101]:
fund_master["expense_ratio_pct"].describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [102]:
fund_master["amfi_code"].nunique()

40

# Save Cleaned Dataset

In [103]:
fund_master.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_fund_master.csv",index=False)

# aum by fund house dataset

In [105]:
aum_fund = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\03_aum_by_fund_house.csv")

In [108]:
aum_fund.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [121]:
aum_fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     datetime64[us]
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 3.6 KB

In [114]:
aum_fund.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [120]:
aum_fund["date"] = pd.to_datetime(aum_fund["date"])

In [115]:
aum_fund.duplicated().sum()

np.int64(0)

In [130]:
aum_fund.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_aum_by_fund_house.csv",index=False)

# monthly sip inflows dataset

In [117]:
sip_monthly = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\04_monthly_sip_inflows.csv")

In [118]:
sip_monthly.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [124]:
sip_monthly.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     datetime64[us]
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: datetime64[us](1), float64(4), int64(1)
memory usage: 2.4 KB

In [123]:
sip_monthly["month"] = pd.to_datetime(sip_monthly["month"])

In [ ]:
sip_monthly.isnull().sum()

# yoy_growth_pct contains 12 null values.

# These values occur because prior-year data is unavailable for the first 12 months of the dataset.

# The values were retained as NULL since Year-over-Year growth cannot be calculated.

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [128]:
sip_monthly.duplicated().sum()

np.int64(0)

In [131]:
sip_monthly.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_monthly_sip_inflows.csv",index=False)

# Category Inflows Dataset

In [132]:
category = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\05_category_inflows.csv")

In [133]:
category.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [136]:
category.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    datetime64[us]
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 3.5 KB

In [135]:
category["month"] = pd.to_datetime(category["month"])

In [137]:
category.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [138]:
category.duplicated().sum()

np.int64(0)

In [139]:
category.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_category_inflows.csv",index=False)

# Industry Folio Count Dataset

In [140]:
industry = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\06_industry_folio_count.csv")

In [141]:
industry.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [144]:
industry.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     datetime64[us]
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: datetime64[us](1), float64(5)
memory usage: 1.1 KB

In [143]:
industry["month"] = pd.to_datetime(industry["month"])

In [145]:
industry.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [146]:
industry.duplicated().sum()

np.int64(0)

In [147]:
industry.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_industry_folio_count.csv",index=False)

# Portfolio Holdings Dataset

In [148]:
portfolio = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\09_portfolio_holdings.csv")

In [149]:
portfolio.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [152]:
portfolio.info()

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(1), str(3)
memory usage: 20.3 KB

In [151]:
portfolio["portfolio_date"] = pd.to_datetime(portfolio["portfolio_date"])

In [153]:
portfolio.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [154]:
portfolio.duplicated().sum()

np.int64(0)

In [155]:
portfolio.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_portfolio_holdings.csv",index=False)

# Benchmark Indices

In [156]:
benchmark = pd.read_csv(r"D:\bluestock_mf_capstone\data\raw\10_benchmark_indices.csv")

In [157]:
benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [161]:
benchmark.info()

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   datetime64[us]
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 188.8 KB

In [160]:
benchmark["date"] = pd.to_datetime(benchmark["date"])

In [162]:
benchmark.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [163]:
benchmark.duplicated().sum()

np.int64(0)

In [164]:
benchmark.to_csv(r"D:\bluestock_mf_capstone\data\processed/clean_benchmark_indices.csv",index=False)